server {
    listen 80 default_server;

    server_name _;

    location / {
        root /www;

        index index.html;
        # Directs Nginx to fall back to index.html for React Router paths
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://api/;
    }
}

